#
# Example of how to run network-failure-simulator with other alpine-based containers
# Please ensure all your containers have NET_ADMIN capability added,
# otherwise any traffic shaping commands are ignored silently!
#
version: "3.7"

services:

  #
  # Sample container, continuously sends ping to google.com.
  # The output prints ping delay in milliseconds, this makes it ideal for testing network delays.
  #
  ping-google:
    image: "alpine"
    container_name: ping-google
    # IMPORTANT - all your containers should have this option enabled!
    cap_add:
      - NET_ADMIN
    entrypoint: [sh, -c, "apk add --update iproute2 && ping gooogle.com"]

  #
  # Webapp/UI - http://localhost:8080
  #
  docker-network-failure-simulator:
    image: agladkowski/docker-network-failure-simulator
    container_name: docker-network-failure-simulator
    ports:
    - "8080:8080"

    # IMPORTANT - network failure simulator needs to access docker-demon to see all the containers
    # and execute network traffic shaping commands!
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
